import {providers} from './providers.js';
const TTL=36e5,cache=new Map(),last={},RPM={nasa:60,wikimedia:60,archive:30,pexels:60,pixabay:60,unsplash:30,openverse:10,flickr:60};
const cached=async(k,fn)=>{const h=cache.get(k);if(h&&Date.now()-h.t<TTL)return h.v;const v=await fn();if(cache.size>500)cache.clear();cache.set(k,{t:Date.now(),v});return v};
const gate=async n=>{const w=Math.max(0,(last[n]||0)+60000/(RPM[n]||30)-Date.now());last[n]=Date.now()+w;if(w)await new Promise(r=>setTimeout(r,w))};
const GL=[[/كتكوت|كتاكيت|صوص|فراخ صغيرة/,'baby chicks'],[/دجاج|فراخ|فرخة/,'chicken'],[/سمان/,'quail'],[/ديك رومي/,'turkey'],[/ديك(?! رومي)/,'rooster'],[/بط/,'duck'],[/إوز|اوز/,'goose'],[/حمام/,'pigeon'],[/أرنب|ارانب/,'rabbit'],[/بيض/,'eggs'],[/تفقيس|فقس/,'hatching'],[/حاضنة/,'incubator'],[/علف|تغذية|أكل/,'feeding'],[/عشة|قن|مجثم|حظيرة/,'chicken coop'],[/مزرعة/,'farm'],[/حرارة|تدفئة|مصدر حراري/,'heat lamp'],[/بيطري|مرض/,'veterinary']];
const PROMPT=sc=>`You are a visual director for poultry, livestock and farming educational videos. Narration (any language, may be Egyptian Arabic): ${JSON.stringify(sc.narration)}\nDecide what the viewer should SEE. Identify the animal (chicken chick, hen, rooster, quail, duck, turkey, goose, pigeon...), the topic (brooding, laying, incubation, feeding, housing, health...) and the visual needs. Never search the full sentence: turn the meaning into short English stock-footage queries (2-4 words), e.g. "baby chicks brooder", "chicks under heat lamp", "broody hen eggs", "quail laying eggs", "chicken coop".\nReply with ONLY JSON: {"sceneType":"video|image|chart|diagram|map|document|archival","animal":"","topic":"","queries":[5 queries, most specific first]}. Use "chart" when the narration states statistics or percentages, "video" for actions (laying, feeding, hatching).`;
const parseAI=t=>{const o=JSON.parse((t||'').match(/\{[\s\S]*\}/)[0]);if(!Array.isArray(o.queries)||!o.queries.length)throw new Error('no queries returned');return o};
const askClaude=async p=>{const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':process.env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},signal:AbortSignal.timeout(20000),body:JSON.stringify({model:process.env.ANTHROPIC_MODEL||'claude-sonnet-5-5',max_tokens:500,messages:[{role:'user',content:p}]})});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'HTTP '+r.status);return j.content?.find(c=>c.type==='text')?.text};
const askGemini=async p=>{let err;for(const m of[process.env.GEMINI_MODEL,'gemini-2.5-flash','gemini-3.5-flash'].filter(Boolean)){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${m}:generateContent`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':process.env.GEMINI_API_KEY},signal:AbortSignal.timeout(30000),body:JSON.stringify({contents:[{parts:[{text:p}]}],generationConfig:{responseMimeType:'application/json',temperature:.3}})});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'HTTP '+r.status);return(j.candidates?.[0]?.content?.parts||[]).map(x=>x.text||'').join('')}catch(e){err=e}}throw err};
export async function genQueries(sc){const order=[['gemini',process.env.GEMINI_API_KEY,askGemini],['anthropic',process.env.ANTHROPIC_API_KEY,askClaude]].filter(x=>x[1]);if(process.env.AI_PROVIDER==='anthropic')order.reverse();
 for(const[name,,ask]of order){try{const o=parseAI(await ask(PROMPT(sc)));return{queries:o.queries.slice(0,5).map(String),type:sc.assetType||(['video','image'].includes(o.sceneType)?o.sceneType:'any'),sceneType:o.sceneType,animal:o.animal,topic:o.topic,via:name}}catch(e){console.warn(name+' query generation failed:',e.message)}}
 const f=[...new Set(GL.filter(([r])=>r.test(sc.narration)).map(x=>x[1]))],latin=(sc.narration.match(/[A-Za-z0-9]{3,}/g)||[]).join(' '),k=sc.keywords||[];
 const qs=[f.slice(0,3).join(' '),f.slice(0,2).join(' '),f[0]&&f[0]+' farm',latin,k.slice(0,2).join(' ')].map(x=>(x||'').trim()).filter(Boolean);
 return{queries:[...new Set(qs)],type:sc.assetType||'any',via:'heuristic'}}
export const licenseScore=l=>/-nc|-nd|\bnc\b|\bnd\b|noncommercial|noderiv/i.test(l||'')?0:/public domain|cc0|government work|pexels|pixabay|unsplash/i.test(l||'')?1:/cc[- ]by/i.test(l||'')?.8:/no known copyright/i.test(l||'')?.6:0;
const tok=s=>(s||'').toLowerCase().match(/[\p{L}\p{N}]{3,}/gu)||[],STOCK=new Set(['pexels','pixabay','unsplash']);
export function rank(list,{queries,narration,dur}){const years=narration.match(/\b(1[5-9]\d\d|20\d\d)\b/g)||[],qt=queries.map(q=>new Set(tok(q)));
 return list.map(a=>{const at=new Set(tok(a.text||a.title)),m=qt.map(s=>s.size?[...s].filter(t=>at.has(t)).length/s.size:0),queryMatch=Math.max(0,...m),relevance=Math.min(1,m.reduce((x,y)=>x+y,0)/Math.max(1,m.length)*1.5);
  const resolution=a.width?Math.min(1,a.width*a.height/(1280*720)):.5,fit=a.type==='video'&&a.duration?Math.min(1,a.duration/dur):1,quality=(resolution+fit)/2,reliability=a.reliability??.5,license=licenseScore(a.license);
  let context=1;if(years.length){const b=`${a.text} ${a.date}`;context=years.some(y=>b.includes(y))?1:STOCK.has(a.source.toLowerCase())?.1:.5}
  const score=.35*relevance+.15*reliability+.15*quality+.1*license+.15*context+.1*queryMatch;return{...a,score,breakdown:{relevance,reliability,quality,license,context,queryMatch}}}).sort((x,y)=>y.score-x.score)}
const filt=l=>[...new Map(l.map(a=>[a.id,a])).values()].filter(a=>licenseScore(a.license)>0&&a.thumbnail&&(a.type!=='image'||!a.width||a.width>=640));
export async function searchScene(sc){const gq=await genQueries(sc),errors=[],counts={},dur=Math.max(1,(sc.endTime-sc.startTime)||5);
 const run=async(qs,type)=>{const jobs=providers.filter(p=>p.enabled()).flatMap(p=>qs.map(q=>cached(`${p.name}|${type}|${q}`,async()=>{await gate(p.name);return(await p.search(q,{type})).map(a=>({...a,provider:p.name,reliability:p.reliability}))}).catch(e=>{errors.push(`${p.name}: ${e.message}`);return[]})));const r=(await Promise.all(jobs)).flat();r.forEach(a=>counts[a.provider]=(counts[a.provider]||0)+1);return r};
 const attempt=async type=>{let raw=await run(gq.queries,type),list=filt(raw);if(!list.length&&gq.queries.length>1){raw=raw.concat(await run([gq.queries.at(-1)],type));list=filt(raw)}
  const ranked=rank(list,{queries:gq.queries,narration:sc.narration,dur}).filter(a=>a.breakdown.relevance>=.25);let asset=null;
  for(const c of ranked.slice(0,3)){try{const r=await providers.find(p=>p.name===c.provider).resolve?.(c)??c;if(r.mediaUrl){asset=r;break}}catch(e){errors.push(`resolve ${c.provider}: ${e.message}`)}}
  return{asset,ranked,unclear:raw.filter(a=>licenseScore(a.license)===0).length}};
 let r;for(const t of gq.type==='video'?['video','image']:gq.type==='any'?['any']:[gq.type,'any']){r=await attempt(t);if(r.asset)break}
 return{asset:r.asset,alternatives:r.ranked.filter(a=>a.mediaUrl&&a.id!==r.asset?.id).slice(0,6),queries:gq.queries,via:gq.via,sceneType:gq.sceneType,animal:gq.animal,topic:gq.topic,counts,errors,reason:r.asset?'':(r.unclear?'License unclear — not selected automatically.':'No suitable licensed visual found.')}}
