const UA='SceneBuilder/1.0 (set-your-contact-email)',E=encodeURIComponent,strip=s=>(s||'').replace(/<[^>]*>/g,'').trim();
const jget=async(url,h={})=>{const r=await fetch(url,{headers:{'user-agent':UA,...h},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`HTTP ${r.status} ${url.split('?')[0]}`);return r.json()};
const licName=u=>/publicdomain|zero/i.test(u)?'Public Domain / CC0':(u.match(/licenses\/([a-z-]+)/i)||[])[1]?'CC '+u.match(/licenses\/([a-z-]+)/i)[1].toUpperCase():'';
const A=o=>({creator:'',licenseUrl:'',width:null,height:null,duration:null,date:'',...o});
// Unified result: {id,title,text,thumbnail,mediaUrl,type,source,sourceUrl,creator,license,licenseUrl,width,height,duration,date}
export const providers=[
{name:'nasa',reliability:1,enabled:()=>true,
 async search(q,o){const mt=o.type==='video'?'video':o.type==='image'?'image':'image,video';
  const j=await jget(`https://images-api.nasa.gov/search?q=${E(q)}&media_type=${mt}&page_size=10`);
  return j.collection.items.map(i=>{const d=i.data[0],th=i.links?.[0]?.href;return A({id:'nasa:'+d.nasa_id,title:d.title,text:`${d.title} ${d.description||''} ${(d.keywords||[]).join(' ')}`,thumbnail:th,mediaUrl:d.media_type==='image'&&th?th.replace('~thumb','~medium'):null,manifest:i.href,type:d.media_type,source:'NASA',sourceUrl:'https://images.nasa.gov/details/'+E(d.nasa_id),creator:d.photographer||d.secondary_creator||d.center||'NASA',license:'Public Domain (NASA)',licenseUrl:'https://www.nasa.gov/nasa-brand-center/images-and-media/',date:d.date_created||''})})},
 async resolve(a){if(a.mediaUrl||!a.manifest)return a;const f=await jget(a.manifest.replace('http://','https://')),u=f.find(x=>/~(medium|mobile)\.mp4$/.test(x))||f.find(x=>/\.mp4$/.test(x));return u?{...a,mediaUrl:u.replace('http://','https://')}:a}},
{name:'wikimedia',reliability:.9,enabled:()=>true,
 async search(q,o){const j=await jget(`https://commons.wikimedia.org/w/api.php?action=query&format=json&generator=search&gsrnamespace=6&gsrlimit=10&gsrsearch=${E(q+(o.type==='video'?' filetype:video':' filetype:bitmap'))}&prop=imageinfo&iiprop=url|size|mime|extmetadata&iiurlwidth=1600`);
  return Object.values(j.query?.pages||{}).map(p=>{const i=p.imageinfo?.[0];if(!i)return null;const m=i.extmetadata||{},v=/^video|ogg/.test(i.mime);return A({id:'wm:'+p.pageid,title:p.title.replace(/^File:/,''),text:`${p.title} ${strip(m.ImageDescription?.value)} ${strip(m.Categories?.value)}`,thumbnail:i.thumburl||i.url,mediaUrl:v?i.url:(i.thumburl||i.url),type:v?'video':'image',source:'Wikimedia Commons',sourceUrl:i.descriptionurl,creator:strip(m.Artist?.value),license:strip(m.LicenseShortName?.value),licenseUrl:m.LicenseUrl?.value||'',width:i.width,height:i.height,date:strip(m.DateTimeOriginal?.value)})}).filter(Boolean)}},
{name:'archive',reliability:.8,enabled:()=>true,
 async search(q,o){const mt=o.type==='video'?'movies':o.type==='image'?'image':'(movies OR image)';
  const j=await jget(`https://archive.org/advancedsearch.php?q=${E(`(${q}) AND mediatype:${mt}`)}&fl[]=identifier&fl[]=title&fl[]=description&fl[]=creator&fl[]=licenseurl&fl[]=mediatype&fl[]=date&rows=10&output=json`);
  return j.response.docs.map(d=>A({id:'ia:'+d.identifier,title:d.title,text:`${d.title} ${[].concat(d.description||[]).join(' ').slice(0,300)}`,thumbnail:'https://archive.org/services/img/'+d.identifier,type:d.mediatype==='movies'?'video':'image',source:'Internet Archive',sourceUrl:'https://archive.org/details/'+d.identifier,creator:[].concat(d.creator||[]).join(', '),license:d.licenseurl?licName(d.licenseurl):'',licenseUrl:d.licenseurl||'',date:d.date||''}))},
 async resolve(a){const id=a.id.slice(3),j=await jget('https://archive.org/metadata/'+id),f=j.files||[],p=a.type==='video'?f.find(x=>/\.mp4$/i.test(x.name)):f.find(x=>/\.jpe?g$/i.test(x.name));return p?{...a,mediaUrl:`https://archive.org/download/${id}/${E(p.name)}`}:a}},
{name:'pexels',reliability:.7,enabled:()=>!!process.env.PEXELS_API_KEY,
 async search(q,o){const h={Authorization:process.env.PEXELS_API_KEY},out=[],L='Pexels License',LU='https://www.pexels.com/license/';
  if(o.type!=='image'){const j=await jget(`https://api.pexels.com/videos/search?query=${E(q)}&per_page=8`,h);for(const v of j.videos){const f=v.video_files.filter(x=>x.file_type==='video/mp4'&&x.width<=1920).sort((a,b)=>b.width-a.width)[0];if(f)out.push(A({id:'px:v'+v.id,title:v.url.split('/').filter(Boolean).pop().replace(/-/g,' '),text:v.url.split('/').filter(Boolean).pop().replace(/-/g,' '),thumbnail:v.image,mediaUrl:f.link,type:'video',source:'Pexels',sourceUrl:v.url,creator:v.user.name,license:L,licenseUrl:LU,width:f.width,height:f.height,duration:v.duration}))}}
  if(o.type!=='video'){const j=await jget(`https://api.pexels.com/v1/search?query=${E(q)}&per_page=8`,h);for(const p of j.photos)out.push(A({id:'px:p'+p.id,title:p.alt||'',text:`${p.alt||''} ${p.url.split('/').filter(Boolean).pop().replace(/-/g,' ')}`,thumbnail:p.src.medium,mediaUrl:p.src.large2x,type:'image',source:'Pexels',sourceUrl:p.url,creator:p.photographer,license:L,licenseUrl:LU,width:p.width,height:p.height}))}
  return out}},
{name:'pixabay',reliability:.65,enabled:()=>!!process.env.PIXABAY_API_KEY,
 async search(q,o){const k=process.env.PIXABAY_API_KEY,s=E(q.slice(0,100)),out=[],L='Pixabay Content License',LU='https://pixabay.com/service/license-summary/';
  if(o.type!=='image'){const j=await jget(`https://pixabay.com/api/videos/?key=${k}&q=${s}&per_page=8`);for(const h of j.hits){const v=h.videos.large?.url?h.videos.large:h.videos.medium;out.push(A({id:'pb:v'+h.id,title:h.tags,text:h.tags,thumbnail:v.thumbnail,mediaUrl:v.url,type:'video',source:'Pixabay',sourceUrl:h.pageURL,creator:h.user,license:L,licenseUrl:LU,width:v.width,height:v.height,duration:h.duration}))}}
  if(o.type!=='video'){const j=await jget(`https://pixabay.com/api/?key=${k}&q=${s}&image_type=photo&per_page=8&min_width=1280`);for(const h of j.hits)out.push(A({id:'pb:p'+h.id,title:h.tags,text:h.tags,thumbnail:h.webformatURL,mediaUrl:h.largeImageURL,type:'image',source:'Pixabay',sourceUrl:h.pageURL,creator:h.user,license:L,licenseUrl:LU,width:h.imageWidth,height:h.imageHeight}))}
  return out}},
{name:'unsplash',reliability:.7,enabled:()=>!!process.env.UNSPLASH_API_KEY,
 async search(q,o){if(o.type==='video')return[];const j=await jget(`https://api.unsplash.com/search/photos?query=${E(q)}&per_page=8`,{Authorization:'Client-ID '+process.env.UNSPLASH_API_KEY});
  return j.results.map(p=>A({id:'us:'+p.id,title:p.description||p.alt_description||'',text:`${p.description||''} ${p.alt_description||''}`,thumbnail:p.urls.small,mediaUrl:p.urls.regular,type:'image',source:'Unsplash',sourceUrl:p.links.html,creator:p.user.name,license:'Unsplash License',licenseUrl:'https://unsplash.com/license',width:p.width,height:p.height}))}},
{name:'openverse',reliability:.75,enabled:()=>true,
 async search(q,o){if(o.type==='video')return[];const j=await jget(`https://api.openverse.org/v1/images/?q=${E(q)}&license_type=commercial,modification&page_size=10`);
  return j.results.map(r=>{const ok=/^https:\/\/(upload\.wikimedia\.org|live\.staticflickr\.com)\//.test(r.url),L=r.license==='cc0'?'CC0':r.license==='pdm'?'Public Domain Mark':`CC ${r.license.toUpperCase()} ${r.license_version||''}`.trim();return A({id:'ov:'+r.id,title:r.title||'',text:`${r.title||''} ${(r.tags||[]).map(t=>t.name).join(' ')}`,thumbnail:r.thumbnail,mediaUrl:ok?r.url:r.thumbnail,type:'image',source:'Openverse / '+(r.source||''),sourceUrl:r.foreign_landing_url,creator:r.creator||'',license:L,licenseUrl:r.license_url||'',width:ok?r.width:null,height:ok?r.height:null})})}},
{name:'flickr',reliability:.6,enabled:()=>!!process.env.FLICKR_API_KEY,
 async search(q,o){if(o.type==='video')return[];const N={4:'CC BY 2.0',5:'CC BY-SA 2.0',7:'No known copyright restrictions',8:'United States Government Work',9:'CC0',10:'Public Domain Mark'};
  const j=await jget(`https://www.flickr.com/services/rest/?method=flickr.photos.search&api_key=${process.env.FLICKR_API_KEY}&text=${E(q)}&license=4,5,7,8,9,10&media=photos&sort=relevance&per_page=10&extras=license,owner_name,url_l,url_c,description&format=json&nojsoncallback=1`);
  return(j.photos?.photo||[]).filter(x=>x.url_l||x.url_c).map(x=>A({id:'fl:'+x.id,title:x.title,text:`${x.title} ${x.description?._content||''}`,thumbnail:x.url_c||x.url_l,mediaUrl:x.url_l||x.url_c,type:'image',source:'Flickr',sourceUrl:`https://www.flickr.com/photos/${x.owner}/${x.id}`,creator:x.ownername,license:N[x.license]||'',licenseUrl:'https://www.flickr.com/commons/usage/',width:+(x.width_l||x.width_c),height:+(x.height_l||x.height_c)}))}}
];
