import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {Readable} from 'node:stream';import {fileURLToPath,pathToFileURL} from 'node:url';import {searchScene} from './engine.js';
const here=path.dirname(fileURLToPath(import.meta.url));
const HOSTS=/^(upload\.wikimedia\.org|images\.pexels\.com|videos\.pexels\.com|cdn\.pixabay\.com|images\.unsplash\.com|images-assets\.nasa\.gov|api\.openverse\.org|live\.staticflickr\.com|([a-z0-9-]+\.)?archive\.org)$/;
const KEYS=['GEMINI_API_KEY','ANTHROPIC_API_KEY','OPENAI_API_KEY','PEXELS_API_KEY','PIXABAY_API_KEY','UNSPLASH_API_KEY','FLICKR_API_KEY'];
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png'};
const hits=new Map(),send=(r,c,o)=>{r.writeHead(c,{'content-type':'application/json'});r.end(JSON.stringify(o))};
const rl=ip=>{const n=Date.now(),a=(hits.get(ip)||[]).filter(t=>n-t<6e4);a.push(n);hits.set(ip,a);return a.length<=120};
const raw=(req,max)=>new Promise((ok,no)=>{const c=[];let n=0;req.on('data',d=>{n+=d.length;if(n>max){no(new Error('too large'));req.destroy()}else c.push(d)});req.on('end',()=>ok(Buffer.concat(c)));req.on('error',no)});
const json=async req=>{const b=await raw(req,1e6);try{return JSON.parse(b.toString())}catch{throw new Error('invalid JSON')}};
const clean=s=>{if(typeof s.narration!=='string'||!s.narration.trim()||s.narration.length>1500)throw new Error('narration required (max 1500 chars)');return{narration:s.narration,keywords:(Array.isArray(s.keywords)?s.keywords:[]).slice(0,8).map(String),startTime:+s.startTime||0,endTime:+s.endTime||0,assetType:['video','image'].includes(s.assetType)?s.assetType:undefined}};
function saveKeys(dir,b){const f=path.join(dir,'.env'),cur=Object.fromEntries((fs.existsSync(f)?fs.readFileSync(f,'utf8'):'').split('\n').map(l=>l.split(/=(.*)/s)).filter(x=>KEYS.includes(x[0])));for(const k of KEYS)if(typeof b[k]==='string'&&/^[\w.\-]{8,200}$/.test(b[k])){cur[k]=b[k];process.env[k]=b[k]}fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(f,Object.entries(cur).map(([k,v])=>`${k}=${v}`).join('\n')+'\n',{mode:0o600})}
export const start=({port=+process.env.PORT||3000,dataDir=process.env.DATA_DIR||here,publicDir=path.join(here,'public')}={})=>{
 try{process.loadEnvFile(path.join(dataDir,'.env'))}catch{}
 const srv=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x'),P=srv.address().port;if(!rl(req.socket.remoteAddress))return send(res,429,{error:'rate limit'});
  if(req.method==='POST'){const o=req.headers.origin;if(o&&o!==`http://127.0.0.1:${P}`&&o!==`http://localhost:${P}`)return send(res,403,{error:'forbidden origin'})}
  if(req.method==='GET'&&u.pathname==='/api/settings')return send(res,200,{configured:Object.fromEntries(KEYS.map(k=>[k,!!process.env[k]]))});
  if(req.method==='POST'&&u.pathname==='/api/settings'){saveKeys(dataDir,await json(req));return send(res,200,{ok:true})}
  if(req.method==='GET'&&u.pathname==='/api/media'){const t=new URL(u.searchParams.get('u'));if(t.protocol!=='https:'||!HOSTS.test(t.hostname))return send(res,400,{error:'host not allowed'});const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),30000);let r;try{r=await fetch(t,{signal:ac.signal})}finally{clearTimeout(tm)}res.writeHead(r.status,{'content-type':r.headers.get('content-type')||'application/octet-stream'});const s=Readable.fromWeb(r.body);s.on('error',()=>res.destroy());res.on('close',()=>s.destroy());return s.pipe(res)}
  if(req.method==='POST'&&u.pathname==='/api/transcribe'){const key=process.env.OPENAI_API_KEY;if(!key)return send(res,400,{error:'OPENAI_API_KEY is not set (add it in Settings)'});const buf=await raw(req,25e6),name=decodeURIComponent(req.headers['x-filename']||'audio.mp3').replace(/[^\w.\-]/g,'_'),fd=new FormData();fd.append('file',new Blob([buf],{type:req.headers['content-type']||'audio/mpeg'}),name);fd.append('model','whisper-1');fd.append('response_format','verbose_json');fd.append('timestamp_granularities[]','segment');
   const r=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{authorization:'Bearer '+key},body:fd,signal:AbortSignal.timeout(3e5)}),j=await r.json();if(!r.ok)return send(res,502,{error:j.error?.message||'transcription failed'});return send(res,200,{text:j.text,segments:(j.segments||[]).map(s=>({start:s.start,end:s.end,text:s.text}))})}
  if(req.method==='POST'&&u.pathname==='/api/search-scene')return send(res,200,await searchScene(clean(await json(req))));
  if(req.method==='POST'&&u.pathname==='/api/generate'){const b=await json(req);if(!Array.isArray(b.scenes)||b.scenes.length>60)return send(res,400,{error:'scenes[] required (max 60)'});const out=[];for(const s of b.scenes){out.push({id:s.id,...await searchScene(clean(s))})}return send(res,200,{scenes:out})}
  if(req.method==='GET'){const f=path.join(publicDir,path.normalize(u.pathname==='/'?'/index.html':u.pathname));if(!f.startsWith(publicDir+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile())return send(res,404,{error:'not found'});res.writeHead(200,{'content-type':MIME[path.extname(f)]||'application/octet-stream'});return res.end(fs.readFileSync(f))}
  send(res,404,{error:'not found'})}catch(e){send(res,/required|invalid|too large/.test(e.message)?400:500,{error:e.message})}});
 return new Promise(ok=>srv.listen(port,'127.0.0.1',()=>ok(srv.address().port)))};
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)start().then(p=>console.log('http://127.0.0.1:'+p));
